#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: #@ data.values.certificate.values.secret_name
  namespace: #@ data.values.certificate.values.namespace
spec:
  commonName: #@ data.values.tap_install.values.shared.ingress_domain
  dnsNames:
  - #@ "*.{}".format(data.values.tap_install.values.shared.ingress_domain)
  - #@ "*.learningcenter.{}".format(data.values.tap_install.values.shared.ingress_domain)
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject:
    organizations:
    - vmware
  renewBefore: 360h0m0s
  secretName: #@ data.values.certificate.values.secret_name