#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
  namespace: #@ data.values.certificate.values.namespace
spec:
  acme:
    email: #@ data.values.certificate.values.issuer.email
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            region: #@ data.values.certificate.values.issuer.route53.region
            hostedZoneID: #@ data.values.certificate.values.issuer.route53.route_fifty_three_zone_id
            role: #@ data.values.certificate.values.issuer.route53.externalDnsRoleArn
            accessKeyIDSecretRef:
              name: certificate-sensitive-values
              key: issuer-route53-access-key-id
            secretAccessKeySecretRef:
              name: certificate-sensitive-values
              key: issuer-route53-access-key-secret