#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: certificate-secrets
  namespace: #@ data.values.certificate.values.namespace
spec:
  provider:
    aws:
      service: SecretsManager
      region: #@ data.values.certificate.secrets.eso.aws.region
      auth:
        jwt:
          serviceAccountRef:
            name: certificate-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: #@ data.values.certificate.secrets.eso.aws.certificate_secrets.role_arn
  name: certificate-secrets
  namespace: #@ data.values.certificate.values.namespace
