#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: contour-internal-values
  namespace: tap-install
stringData:
  values.yaml: #@ yaml.encode(data.values.internal-contour.values)
