apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: ingress-internal-class-name-overlay
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.1: ingress-internal-envoy-service-type-overlay
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.2: ingress-internal-fix-multiple-instances-overlay
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgi"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgi"
  name: contour-internal
  namespace: tap-install
spec:
  packageRef:
    refName: contour.tanzu.vmware.com
    versionSelection:
      constraints: #@ data.values.internal-contour.version.package_version
  serviceAccountName: tap-installer-sa
  values:
  - secretRef:
      name: contour-internal-values